export type SpringEpisode = {
  work: string;
  number: number;
  label: string;
  title: string;
  airtime: string;
  summary: string;
  characters: string[];
  keywords: string[];
  sourceUrl: string;
};

export type SpringCatalogWork = {
  title: string;
  period: "2026年春";
  sourceUrl: string;
};

const springCatalogSource = "https://www.animatetimes.com/tag/details.php?id=5228";

export const springCatalog: SpringCatalogWork[] = [
  "愛してるゲームを終わらせたい",
  "あかね噺",
  "淡島百景",
  "異世界のんびり農家2",
  "一畳間まんきつ暮らし！",
  "嫌な顔されながらおパンツ見せてもらいたいR",
  "インゴクダンチ",
  "うそ探偵トマント",
  "大きい女の子は好きですか？",
  "おジャ魔女どれみにょん",
  "オタクに優しいギャルはいない!?",
  "おでかけ子ザメ シーズン2",
  "お隣の天使様にいつの間にか駄目人間にされていた件 第2期",
  "おねがいアイプリ",
  "カナン様はあくまでチョロい",
  "彼女、お借りします 第5期",
  "上伊那ぼたん、酔へる姿は百合の花",
  "神の雫",
  "神の庭付き楠木邸",
  "ガンバレ！中村くん!!",
  "キャンディーカリエス",
  "霧尾ファンクラブ",
  "キルアオ",
  "クジマ歌えば家ほろろ",
  "クマーバ シーズン3",
  "クラスで2番目に可愛い女の子と友だちになった",
  "黒猫と魔女の教室",
  "ゴーストコンサート : missing Songs",
  "氷の城壁",
  "こめかみっ！ガールズ",
  "こんなこいるかな",
  "最強の王様、二度目の人生は何をする？ Season2",
  "最強の職業は勇者でも賢者でもなく鑑定士(仮)らしいですよ？",
  "サク山チョコ次郎",
  "自称悪役令嬢な婚約者の観察記録。",
  "自動販売機に生まれ変わった俺は迷宮を彷徨う 3rd season",
  "終末のワルキューレIII",
  "春夏秋冬代行者 春の舞",
  "小3アシベ QQゴマちゃん",
  "スター・ウォーズ：モール／シャドウ・ロード",
  "スティール・ボール・ラン ジョジョの奇妙な冒険",
  "スノウボールアース",
  "大賢者リドルの時間逆行",
  "ダイヤのA actII Second Season",
  "ただいま、おじゃまされます！",
  "だんでらいおん",
  "杖と剣のウィストリア シーズン2",
  "デザート キャッチ！ティニピン",
  "転生したらスライムだった件 第4期",
  "Dr.STONE SCIENCE FUTURE 第3クール",
  "トランスフォーマー ワイルドキングW",
  "ドロヘドロ Season2",
  "とんがり帽子のアトリエ",
  "NEEDY GIRL OVERDOSE",
  "逃がした魚は大きかったが釣りあげた魚が大きすぎた件",
  "日本三國",
  "ニワトリ・ファイター",
  "ネコのクラちゃん～クラレ王国 大陸のLutte Amor～",
  "ねずみくんのチョッキ",
  "灰原くんの強くて青春ニューゲーム",
  "BEASTARS FINAL SEASON Part2",
  "悲劇の元凶となる最強外道ラスボス女王は民の為に尽くします。Season2",
  "左ききのエレン",
  "姫騎士は蛮族（バルバロイ）の嫁",
  "百鬼夜行抄",
  "北斗の拳 -FIST OF THE NORTH STAR-",
  "僕のヒーローアカデミア More",
  "ほっかいどうぶつ",
  "ポンコツ風紀委員とスカート丈が不適切なJKの話",
  "本好きの下剋上 領主の養女",
  "魔入りました！入間くん 第4シリーズ",
  "MAO",
  "また殺されてしまったのですね、探偵様",
  "魔法の姉妹ルルットリリィ",
  "魔物喰らいの冒険者～俺だけ魔物を喰らって強くなる～",
  "茉莉花ちゃんの好感度はぶっ壊れている",
  "マリッジトキシン",
  "メイドさんは食べるだけ",
  "女神『異世界転生何になりたいですか』俺『勇者の肋骨で』",
  "ようこそ実力至上主義の教室へ 4th Season 2年生編1学期",
  "夜桜さんちの大作戦 第2期",
  "黄泉のツガイ",
  "よわよわ先生",
  "LIAR GAME",
  "リィンカーネーションの花弁",
  "Re:ゼロから始める異世界生活 4th season 喪失編",
  "リラックマ",
  "レプリカだって、恋をする。",
].map((title) => ({ title, period: "2026年春", sourceUrl: springCatalogSource }));

export const springWorks = [
  "春夏秋冬代行者 春の舞",
  "ようこそ実力至上主義の教室へ 4th Season 2年生編1学期",
  "とんがり帽子のアトリエ",
];

const fourSeasonsEpisodes: Omit<SpringEpisode, "work">[] = [
  {
    number: 1,
    label: "第壱話",
    title: "春の舞",
    airtime: "2026年3月28日 24:00",
    summary: "十年間春を失った竜宮で、春の代行者・花葉雛菊と護衛官・姫鷹さくらは、春を知らない少女・薺と出会い、この地へ春を呼び戻す儀式に臨む。",
    characters: ["花葉雛菊", "姫鷹さくら", "薺"],
    keywords: ["竜宮", "春顕現", "失われた春", "四季の代行者"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep1",
  },
  {
    number: 2,
    label: "第弐話",
    title: "名残雪",
    airtime: "2026年4月4日 24:00",
    summary: "冬の代行者・寒椿狼星と護衛官・寒月凍蝶は、雛菊の帰還を確かめるため創紫へ向かう。道中で賊の襲撃を退けるが、十年前の傷は冬主従の心に残っていた。",
    characters: ["寒椿狼星", "寒月凍蝶", "石原", "花葉雛菊"],
    keywords: ["創紫", "冬主従", "桜見物", "賊の襲撃"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep2",
  },
  {
    number: 3,
    label: "第参話",
    title: "片影",
    airtime: "2026年4月11日 24:00",
    summary: "衣世の夏離宮を訪れた雛菊とさくらは、護衛官を辞めるという葉桜あやめと、その妹で夏の代行者・葉桜瑠璃の不和を知る。春顕現を進める雛菊には疲労が重なっていく。",
    characters: ["花葉雛菊", "姫鷹さくら", "葉桜あやめ", "葉桜瑠璃"],
    keywords: ["衣世", "夏離宮", "姉妹の不和", "春顕現"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep3",
  },
  {
    number: 4,
    label: "第肆話",
    title: "朝凪",
    airtime: "2026年4月18日 24:00",
    summary: "夏離宮を襲った賊に、姫鷹さくらと葉桜あやめが応戦する。襲撃を退けた後、冬の里からの助力に心を乱すさくらの前へ、葉桜瑠璃が姿を現す。",
    characters: ["姫鷹さくら", "葉桜あやめ", "花葉雛菊", "葉桜瑠璃"],
    keywords: ["夏離宮襲撃", "護衛官", "冬の里", "賊"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep4",
  },
  {
    number: 5,
    label: "第伍話",
    title: "二人ぼっち",
    airtime: "2026年4月25日 24:00",
    summary: "帝州へ向かった雛菊とさくらは、それぞれ過去を振り返る。雛菊は母・紅梅との記憶を、さくらは雛菊との出会いと護衛官になるまでの日々を思い起こす。",
    characters: ["花葉雛菊", "姫鷹さくら", "紅梅", "花葉春月"],
    keywords: ["帝州", "春の里", "過去", "護衛官になるまで"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep5",
  },
  {
    number: 6,
    label: "第陸話",
    title: "還る場所",
    airtime: "2026年5月2日 24:00",
    summary: "帝州で春顕現を続ける雛菊を守りながら、さくらは十年前の誘拐事件と、帰還後に深く傷ついていた雛菊へ寄り添った日々を回想する。",
    characters: ["花葉雛菊", "姫鷹さくら"],
    keywords: ["帝州", "誘拐事件", "帰還", "主従の絆"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep6",
  },
  {
    number: 7,
    label: "第漆話",
    title: "宵闇",
    airtime: "2026年5月9日 24:00",
    summary: "創紫で穏やかに過ごす秋の代行者・祝月撫子と護衛官・阿左美竜胆。一方、冬は春の後ろ盾となるべく動き、春顕現を続ける雛菊の周囲では新たな事態が迫っていた。",
    characters: ["祝月撫子", "阿左美竜胆", "花葉雛菊"],
    keywords: ["創紫", "秋の代行者", "冬の後ろ盾", "急展開"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep7",
  },
  {
    number: 8,
    label: "第捌話",
    title: "桜雨",
    airtime: "2026年5月16日 24:00",
    summary: "秋離宮襲撃の報が広がる中、十年前に冬の里で行われた四季降ろしが描かれる。寒椿狼星は花葉雛菊に心を奪われ、二組の主従は関係を深めていく。",
    characters: ["寒椿狼星", "寒月凍蝶", "花葉雛菊", "姫鷹さくら"],
    keywords: ["秋離宮襲撃", "四季降ろし", "冬の里", "十年前"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep8",
  },
  {
    number: 9,
    label: "第玖話",
    title: "共同戦線",
    airtime: "2026年5月23日 24:00",
    summary: "行方不明となった祝月撫子を救う手立てが見えず、代行者と護衛官たちは苦悩する。寒椿狼星は撫子救出のため、姫鷹さくらへ連絡を入れる。",
    characters: ["祝月撫子", "花葉雛菊", "姫鷹さくら", "阿左美竜胆", "寒椿狼星"],
    keywords: ["撫子誘拐", "共同戦線", "喪失", "救出作戦"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep9",
  },
  {
    number: 10,
    label: "第拾話",
    title: "残像",
    airtime: "2026年5月30日 24:00",
    summary: "四季庁の捜査本部へ雛菊とさくらが合流し、阿左美竜胆を奮い立たせる。やがて撫子をさらった賊の正体と手口が明らかになり、捜査本部に恐怖が走る。",
    characters: ["阿左美竜胆", "花葉雛菊", "姫鷹さくら", "祝月撫子"],
    keywords: ["四季庁", "捜査本部", "賊の正体", "撫子救出"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep10",
  },
  {
    number: 11,
    label: "第拾壱話",
    title: "焦燥",
    airtime: "2026年6月6日 24:00",
    summary: "十年前に雛菊をさらった組織・華歳と、その頭領である観鈴・ヘンダーソンが捜査線上に浮かぶ。春主従が待機する四季庁では、不審な火災が発生する。",
    characters: ["観鈴・ヘンダーソン", "祝月撫子", "花葉雛菊", "姫鷹さくら"],
    keywords: ["華歳", "四季庁火災", "観鈴・ヘンダーソン", "捜査"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep11",
  },
  {
    number: 12,
    label: "第拾弐話",
    title: "襲来",
    airtime: "2026年6月13日 24:00",
    summary: "四季庁へ向かう寒椿狼星と寒月凍蝶の前に、銃を持った石原が立ちはだかる。石原を説き伏せた狼星は、雛菊とさくらのもとへ急ぐため氷の橋を作り出す。",
    characters: ["寒椿狼星", "寒月凍蝶", "石原", "花葉雛菊", "姫鷹さくら"],
    keywords: ["四季庁", "石原の正体", "氷の橋", "冬主従"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep12",
  },
  {
    number: 13,
    label: "第拾参話",
    title: "奪還",
    airtime: "2026年6月20日 24:00",
    summary: "華歳の拠点へ突入した阿左美竜胆と夏主従は、祝月撫子の手掛かりを追う。葉桜瑠璃は姉の葉桜あやめへ撫子救出を命じるが、その決断が危機を招く。",
    characters: ["祝月撫子", "阿左美竜胆", "葉桜瑠璃", "葉桜あやめ"],
    keywords: ["華歳のアジト", "奪還作戦", "夏主従", "銃声"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep13",
  },
  {
    number: 14,
    label: "第拾肆話",
    title: "冬に咲く春の花",
    airtime: "2026年6月27日 24:00",
    summary: "爆弾が仕掛けられた建物で、花葉雛菊は人々を守るため観鈴との対決を決意する。姫鷹さくらへ避難誘導を命じ、寒椿狼星と寒月凍蝶も二人のもとへ向かう。",
    characters: ["花葉雛菊", "観鈴", "姫鷹さくら", "寒椿狼星", "寒月凍蝶"],
    keywords: ["華歳", "爆弾", "君命", "最終話", "避難誘導"],
    sourceUrl: "https://4seasons-anime.com/episode/",
  },
];

const classroomEpisodes: Omit<SpringEpisode, "work">[] = [
  {
    number: 1,
    label: "第1話",
    title: "ホワイトルームからの刺客",
    airtime: "2026年4月1日 22:30〜24:00（初回4話連続）",
    summary: "2年生となりDクラスへ戻った綾小路たちに、全生徒を数値化するOAAが導入される。最初の特別試験は、1年生と2年生がペアを組む筆記試験だった。",
    characters: ["綾小路"],
    keywords: ["OAA", "新入生", "特別試験", "学年混合ペア"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 2,
    label: "第2話",
    title: "契約と代償",
    airtime: "2026年4月1日 22:30〜24:00（初回4話連続）",
    summary: "七瀬と宝泉が去った後、八神が非礼をわびて櫛田へペアを申し出る。堀北たちはDクラスの1年生を中心に、特別試験の協力相手を探し始める。",
    characters: ["七瀬", "宝泉", "八神", "櫛田", "堀北"],
    keywords: ["ペア探し", "契約", "1年Dクラス", "特別試験"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 3,
    label: "第3話",
    title: "リーダーたる覚悟",
    airtime: "2026年4月1日 22:30〜24:00（初回4話連続）",
    summary: "堀北は宝泉との交渉を試みるが、取りつく島もなく断られる。そこへ七瀬が現れ、表に出ない形で交渉を進める案を持ちかける。",
    characters: ["堀北", "宝泉", "七瀬"],
    keywords: ["クラス交渉", "リーダー", "1年Dクラス", "協力関係"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 4,
    label: "第4話",
    title: "刃の向く先",
    airtime: "2026年4月1日 22:30〜24:00（初回4話連続）",
    summary: "宝泉がプライベートポイントを要求する一方、堀北は対等な協力関係を譲らない。七瀬は綾小路から得た情報を手に、交渉を前へ進めようとする。",
    characters: ["堀北", "宝泉", "七瀬", "綾小路"],
    keywords: ["プライベートポイント", "対等な協力", "交渉", "駆け引き"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 5,
    label: "第5話",
    title: "２０００万の男",
    airtime: "2026年4月8日 22:30",
    summary: "綾小路は自分を狙う1年生の策をかわしながら試験へ臨む。だが試験後、2年Dクラスから結果に不正があったのではないかという疑いを向けられる。",
    characters: ["綾小路"],
    keywords: ["2000万ポイント", "不正疑惑", "特別試験", "1年生の策"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 6,
    label: "第6話",
    title: "波乱の争奪戦",
    airtime: "2026年4月15日 22:30",
    summary: "全学年が競う2週間の無人島サバイバル試験が発表される。グループ作りに与えられた4週間で、有力な生徒をめぐる争奪戦が始まる。",
    characters: [],
    keywords: ["無人島サバイバル", "全学年対抗", "グループ作り", "人材争奪"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 7,
    label: "第7話",
    title: "暗躍",
    airtime: "2026年4月22日 22:30",
    summary: "2年生のグループ編成が進む中、1年生各クラスの代表が集まる。宝泉はポイントでの取引がなければ協力しないと主張し、宇都宮が反発する。",
    characters: ["宝泉", "宇都宮"],
    keywords: ["グループ編成", "1年生代表", "ポイント取引", "対立"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 8,
    label: "第8話",
    title: "龍たちの見つめるもの",
    airtime: "2026年4月29日 22:30",
    summary: "桐山は綾小路を呼び出し、南雲へ挑む代わりに試験では干渉しないと告げる。そこへ、学校でも異彩を放つ鬼龍院が姿を見せる。",
    characters: ["桐山", "綾小路", "南雲", "鬼龍院"],
    keywords: ["南雲への挑戦", "不干渉", "鬼龍院", "グループ期限"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 9,
    label: "第9話",
    title: "不穏なる開幕",
    airtime: "2026年5月6日 22:30",
    summary: "無人島サバイバル試験が始まり、移動や課題の達成度がポイントを左右する。月城は監視下でも、生徒同士の小競り合いを一定範囲で認める。",
    characters: ["月城"],
    keywords: ["無人島試験開幕", "腕時計", "指定エリア", "小競り合い"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 10,
    label: "第10話",
    title: "届かぬ想い",
    airtime: "2026年5月13日 22:30",
    summary: "試験2日目、綾小路は七瀬の同行希望を受け入れる。野営予定地には須藤のグループが先着しており、両者はその場で合流する。",
    characters: ["綾小路", "七瀬", "須藤"],
    keywords: ["試験2日目", "同行", "野営地", "グループ合流"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 11,
    label: "第11話",
    title: "縁（えにし）",
    airtime: "2026年5月20日 22:30",
    summary: "綾小路たちは森で倒れている小宮と木下を発見する。小宮は篠原を待っていたところ何者かに殴られ、崖から落ちたと証言する。",
    characters: ["綾小路", "小宮", "木下", "篠原"],
    keywords: ["森の事件", "崖下", "襲撃者", "篠原"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 12,
    label: "第12話",
    title: "怨讐の果てに",
    airtime: "2026年5月27日 22:30",
    summary: "試験7日目、雨を警戒して迂回を提案する綾小路に対し、七瀬は山越えを譲らない。山頂へ着くと、七瀬は綾小路へ胸の内を語り始める。",
    characters: ["綾小路", "七瀬"],
    keywords: ["試験7日目", "雨の山道", "山頂", "七瀬の告白"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 13,
    label: "第13話",
    title: "雨に煙る",
    airtime: "2026年6月3日 22:30",
    summary: "協力を始めた綾小路と七瀬の前へ天沢が現れる。七瀬は小宮と木下の転落現場で見た特徴的な髪の人物が天沢だと考え、問い詰める。",
    characters: ["天沢", "綾小路", "七瀬", "小宮", "木下"],
    keywords: ["天沢との対峙", "転落事件", "雨", "疑惑"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 14,
    label: "第14話",
    title: "孤高の麒麟児",
    airtime: "2026年6月10日 22:30",
    summary: "試験10日目、首位の南雲を高円寺が猛追する。桐山は3年生の6グループを動かして高円寺を止めようとするが、本人は意に介さない。",
    characters: ["南雲", "高円寺", "桐山"],
    keywords: ["首位争い", "高円寺包囲", "3年生", "試験10日目"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 15,
    label: "第15話",
    title: "力と意志",
    airtime: "2026年6月17日 22:30",
    summary: "椿の指示で1年生グループが綾小路を包囲し、指定エリアから外して失格へ追い込もうとする。しかし作戦の最中、包囲する側の動きが突然止まる。",
    characters: ["綾小路", "椿"],
    keywords: ["包囲作戦", "失格狙い", "1年生連合", "作戦停止"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
  {
    number: 16,
    label: "第16話",
    title: "ある未来のために",
    airtime: "2026年6月24日 22:30",
    summary: "一之瀬と南雲に別れを告げた綾小路はI2で待機し、月城と司馬の襲撃を受ける。一方、退学を示唆するメモを得た堀北もI2へ向かう。",
    characters: ["綾小路", "一之瀬", "南雲", "月城", "司馬", "堀北"],
    keywords: ["I2", "月城と司馬", "退学阻止", "最終話"],
    sourceUrl: "https://you-zitsu.com/story.html",
  },
];

const witchHatEpisodes: Omit<SpringEpisode, "work">[] = [
  {
    number: 1,
    label: "第1話",
    title: "はじまりの魔法",
    airtime: "2026年4月6日 23:00",
    summary: "魔法に憧れる村の少女・ココは、旅の魔法使いキーフリーが術を使う瞬間を目撃し、魔法使いたちが守ってきた秘密を知る。",
    characters: ["ココ", "キーフリー"],
    keywords: ["魔法の秘密", "村の少女", "魔法使い", "目撃"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001525",
  },
  {
    number: 2,
    label: "第2話",
    title: "草原の学び舎",
    airtime: "2026年4月13日 23:00",
    summary: "石化した母を救い、幼い頃に会った謎の魔法使いを探すため、ココはキーフリーの弟子となる。アトリエではアガット、テティア、リチェと出会う。",
    characters: ["ココ", "キーフリー", "アガット", "テティア", "リチェ"],
    keywords: ["アトリエ", "弟子入り", "石化", "つばあり帽"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001526",
  },
  {
    number: 3,
    label: "第3話",
    title: "ダダ山脈の試験",
    airtime: "2026年4月20日 23:00",
    summary: "ココを仲間と認められないアガットは、キーフリーの留守中に弟子入り試験「王の許し」へ挑むよう迫る。ココは一人でダダ山脈へ向かう。",
    characters: ["ココ", "アガット", "キーフリー"],
    keywords: ["ダダ山脈", "王の許し", "弟子入り試験", "知らざる者"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001527",
  },
  {
    number: 4,
    label: "第4話",
    title: "カルンでの出会い",
    airtime: "2026年4月27日 23:00",
    summary: "正式な弟子となったココの魔材をそろえるため、一行は魔法使いの街カルンへ出かける。そこでココは、幼い頃に会ったつばあり帽の姿を見つけて追いかける。",
    characters: ["ココ", "キーフリー"],
    keywords: ["カルン", "星の剣", "魔材", "つばあり帽"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001528",
  },
  {
    number: 5,
    label: "第5話",
    title: "巨鱗竜の迷宮",
    airtime: "2026年5月4日 23:00",
    summary: "謎の空間に閉じ込められたココたち四人は、巨鱗竜に阻まれながら脱出の手掛かりとなる魔法陣を目指す。テティアの魔法からココが突破口を思いつく。",
    characters: ["ココ", "アガット", "テティア", "リチェ"],
    keywords: ["巨鱗竜", "迷宮", "脱出", "魔法陣"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001529",
  },
  {
    number: 6,
    label: "第6話",
    title: "雨の日の灯",
    airtime: "2026年5月11日 23:00",
    summary: "キーフリーに救われ日常へ戻ったココは、悩みながらも魔法の練習を続ける。仲間との距離が縮まる中、見張りの眼を務めるオルーギオが姿を現す。",
    characters: ["キーフリー", "ココ", "オルーギオ"],
    keywords: ["魔法の練習", "見張りの眼", "アトリエ", "日常"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001530",
  },
  {
    number: 7,
    label: "第7話",
    title: "誰が為の魔法",
    airtime: "2026年5月18日 23:00",
    summary: "崩れた橋で取り残された人を救うため、キーフリーとオルーギオは現場へ向かう。同行したアガットは補助役を任され、早く実力を示したい焦りを募らせる。",
    characters: ["キーフリー", "オルーギオ", "アガット"],
    keywords: ["救助", "崩落した橋", "魔法器", "焦り"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001531",
  },
  {
    number: 8,
    label: "第8話",
    title: "魔警団の疑念",
    airtime: "2026年5月25日 23:00",
    summary: "ココとアガットはクスタスを救うが、使った魔法が周囲を砂へ変えてしまう。禁止魔法を疑うイースヒースに拘束される中、仲間たちとキーフリーが動く。",
    characters: ["ココ", "アガット", "クスタス", "イースヒース", "リチェ", "テティア", "キーフリー"],
    keywords: ["魔警団", "禁止魔法", "救出", "魔墨"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001532",
  },
  {
    number: 9,
    label: "第9話",
    title: "黒に沈む悪夢",
    airtime: "2026年6月1日 23:00",
    summary: "キーフリーから五芒星試験を聞いた弟子たちは、それぞれの目標を語る。出発点の違いに苦しむココは練習へ没頭し、キーフリーはつばあり帽の痕跡を追う。",
    characters: ["キーフリー", "アガット", "テティア", "リチェ", "ココ"],
    keywords: ["五芒星試験", "悪夢", "知らざる者", "追跡"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001533",
  },
  {
    number: 10,
    label: "第10話",
    title: "銀色の約束",
    airtime: "2026年6月8日 23:00",
    summary: "体調を崩したココはキーフリーとタータに病院へ運ばれる。街の火災で救護が手薄になる中、タータは悪化したココを救う薬を探す。",
    characters: ["ココ", "キーフリー", "タータ"],
    keywords: ["銀彩症", "病院", "街の火災", "薬品庫"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001534",
  },
  {
    number: 11,
    label: "第11話",
    title: "蛇の背洞窟の試験",
    airtime: "2026年6月15日 23:00",
    summary: "教本を熱心に学ぶココとは対照的に、リチェは教本の魔法を拒んでキーフリーと衝突する。そこへ五芒星試験の第二試験開催を知らせる報せが届く。",
    characters: ["ココ", "リチェ", "キーフリー"],
    keywords: ["蛇の背洞窟", "五芒星試験", "教本", "第二試験"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001538",
  },
  {
    number: 12,
    label: "第12話",
    title: "ロモノーンの影",
    airtime: "2026年6月22日 23:00",
    summary: "アガット、リチェ、ユイニィは第二試験「騎士の忠誠」に挑む。アライラの指示を受け、護衛対象に正体を悟られないよう蛇の背洞窟を進む。",
    characters: ["アガット", "リチェ", "ユイニィ", "アライラ"],
    keywords: ["騎士の忠誠", "蛇の背洞窟", "海獣鳥", "第二試験"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001539",
  },
  {
    number: 13,
    label: "第13話",
    title: "禁じられた魔法",
    airtime: "2026年6月29日 23:00",
    summary: "つばあり帽の襲撃でアライラとはぐれた試験組は、力を合わせて追手から逃れる。外で待つココたちも襲われ、二人をかばったキーフリーが重傷を負う。",
    characters: ["アライラ", "アガット", "リチェ", "ユイニィ", "キーフリー", "ココ", "テティア"],
    keywords: ["つばあり帽", "禁じられた魔法", "襲撃", "最終話"],
    sourceUrl: "https://tongari-anime.com/story/detail/?id=1001540",
  },
];

export const springEpisodes: SpringEpisode[] = [
  ...fourSeasonsEpisodes.map((episode) => ({ work: springWorks[0], ...episode })),
  ...classroomEpisodes.map((episode) => ({ work: springWorks[1], ...episode })),
  ...witchHatEpisodes.map((episode) => ({ work: springWorks[2], ...episode })),
];
