export type SpringEpisode = {
  number: number;
  label: string;
  title: string;
  airtime: string;
  summary: string;
  characters: string[];
  keywords: string[];
  sourceUrl: string;
};

export const springWorks = ["春夏秋冬代行者 春の舞"];

export const springEpisodes: SpringEpisode[] = [
  {
    number: 1,
    label: "第壱話",
    title: "春の舞",
    airtime: "2026年3月28日 24:00",
    summary: "十年間春を失った竜宮で、春の代行者・花葉雛菊と護衛官・姫鷹さくらは、春を知らない少女・薺と出会い、この地へ春を呼び戻す儀式に臨む。",
    characters: ["花葉雛菊", "姫鷹さくら", "薺"],
    keywords: ["竜宮", "春顕現", "失われた春", "四季の代行者"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep1",
  },
  {
    number: 2,
    label: "第弐話",
    title: "名残雪",
    airtime: "2026年4月4日 24:00",
    summary: "冬の代行者・寒椿狼星と護衛官・寒月凍蝶は、雛菊の帰還を確かめるため創紫へ向かう。道中で賊の襲撃を退けるが、十年前の傷は冬主従の心に残っていた。",
    characters: ["寒椿狼星", "寒月凍蝶", "石原", "花葉雛菊"],
    keywords: ["創紫", "冬主従", "桜見物", "賊の襲撃"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep2",
  },
  {
    number: 3,
    label: "第参話",
    title: "片影",
    airtime: "2026年4月11日 24:00",
    summary: "衣世の夏離宮を訪れた雛菊とさくらは、護衛官を辞めるという葉桜あやめと、その妹で夏の代行者・葉桜瑠璃の不和を知る。春顕現を進める雛菊には疲労が重なっていく。",
    characters: ["花葉雛菊", "姫鷹さくら", "葉桜あやめ", "葉桜瑠璃"],
    keywords: ["衣世", "夏離宮", "姉妹の不和", "春顕現"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep3",
  },
  {
    number: 4,
    label: "第肆話",
    title: "朝凪",
    airtime: "2026年4月18日 24:00",
    summary: "夏離宮を襲った賊に、姫鷹さくらと葉桜あやめが応戦する。襲撃を退けた後、冬の里からの助力に心を乱すさくらの前へ、葉桜瑠璃が姿を現す。",
    characters: ["姫鷹さくら", "葉桜あやめ", "花葉雛菊", "葉桜瑠璃"],
    keywords: ["夏離宮襲撃", "護衛官", "冬の里", "賊"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep4",
  },
  {
    number: 5,
    label: "第伍話",
    title: "二人ぼっち",
    airtime: "2026年4月25日 24:00",
    summary: "帝州へ向かった雛菊とさくらは、それぞれ過去を振り返る。雛菊は母・紅梅との記憶を、さくらは雛菊との出会いと護衛官になるまでの日々を思い起こす。",
    characters: ["花葉雛菊", "姫鷹さくら", "紅梅", "花葉春月"],
    keywords: ["帝州", "春の里", "過去", "護衛官になるまで"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep5",
  },
  {
    number: 6,
    label: "第陸話",
    title: "還る場所",
    airtime: "2026年5月2日 24:00",
    summary: "帝州で春顕現を続ける雛菊を守りながら、さくらは十年前の誘拐事件と、帰還後に深く傷ついていた雛菊へ寄り添った日々を回想する。",
    characters: ["花葉雛菊", "姫鷹さくら"],
    keywords: ["帝州", "誘拐事件", "帰還", "主従の絆"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep6",
  },
  {
    number: 7,
    label: "第漆話",
    title: "宵闇",
    airtime: "2026年5月9日 24:00",
    summary: "創紫で穏やかに過ごす秋の代行者・祝月撫子と護衛官・阿左美竜胆。一方、冬は春の後ろ盾となるべく動き、春顕現を続ける雛菊の周囲では新たな事態が迫っていた。",
    characters: ["祝月撫子", "阿左美竜胆", "花葉雛菊"],
    keywords: ["創紫", "秋の代行者", "冬の後ろ盾", "急展開"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep7",
  },
  {
    number: 8,
    label: "第捌話",
    title: "桜雨",
    airtime: "2026年5月16日 24:00",
    summary: "秋離宮襲撃の報が広がる中、十年前に冬の里で行われた四季降ろしが描かれる。寒椿狼星は花葉雛菊に心を奪われ、二組の主従は関係を深めていく。",
    characters: ["寒椿狼星", "寒月凍蝶", "花葉雛菊", "姫鷹さくら"],
    keywords: ["秋離宮襲撃", "四季降ろし", "冬の里", "十年前"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep8",
  },
  {
    number: 9,
    label: "第玖話",
    title: "共同戦線",
    airtime: "2026年5月23日 24:00",
    summary: "行方不明となった祝月撫子を救う手立てが見えず、代行者と護衛官たちは苦悩する。寒椿狼星は撫子救出のため、姫鷹さくらへ連絡を入れる。",
    characters: ["祝月撫子", "花葉雛菊", "姫鷹さくら", "阿左美竜胆", "寒椿狼星"],
    keywords: ["撫子誘拐", "共同戦線", "喪失", "救出作戦"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep9",
  },
  {
    number: 10,
    label: "第拾話",
    title: "残像",
    airtime: "2026年5月30日 24:00",
    summary: "四季庁の捜査本部へ雛菊とさくらが合流し、阿左美竜胆を奮い立たせる。やがて撫子をさらった賊の正体と手口が明らかになり、捜査本部に恐怖が走る。",
    characters: ["阿左美竜胆", "花葉雛菊", "姫鷹さくら", "祝月撫子"],
    keywords: ["四季庁", "捜査本部", "賊の正体", "撫子救出"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep10",
  },
  {
    number: 11,
    label: "第拾壱話",
    title: "焦燥",
    airtime: "2026年6月6日 24:00",
    summary: "十年前に雛菊をさらった組織・華歳と、その頭領である観鈴・ヘンダーソンが捜査線上に浮かぶ。春主従が待機する四季庁では、不審な火災が発生する。",
    characters: ["観鈴・ヘンダーソン", "祝月撫子", "花葉雛菊", "姫鷹さくら"],
    keywords: ["華歳", "四季庁火災", "観鈴・ヘンダーソン", "捜査"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep11",
  },
  {
    number: 12,
    label: "第拾弐話",
    title: "襲来",
    airtime: "2026年6月13日 24:00",
    summary: "四季庁へ向かう寒椿狼星と寒月凍蝶の前に、銃を持った石原が立ちはだかる。石原を説き伏せた狼星は、雛菊とさくらのもとへ急ぐため氷の橋を作り出す。",
    characters: ["寒椿狼星", "寒月凍蝶", "石原", "花葉雛菊", "姫鷹さくら"],
    keywords: ["四季庁", "石原の正体", "氷の橋", "冬主従"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep12",
  },
  {
    number: 13,
    label: "第拾参話",
    title: "奪還",
    airtime: "2026年6月20日 24:00",
    summary: "華歳の拠点へ突入した阿左美竜胆と夏主従は、祝月撫子の手掛かりを追う。葉桜瑠璃は姉の葉桜あやめへ撫子救出を命じるが、その決断が危機を招く。",
    characters: ["祝月撫子", "阿左美竜胆", "葉桜瑠璃", "葉桜あやめ"],
    keywords: ["華歳のアジト", "奪還作戦", "夏主従", "銃声"],
    sourceUrl: "https://4seasons-anime.com/episode/?id=ep13",
  },
  {
    number: 14,
    label: "第拾肆話",
    title: "冬に咲く春の花",
    airtime: "2026年6月27日 24:00",
    summary: "爆弾が仕掛けられた建物で、花葉雛菊は人々を守るため観鈴との対決を決意する。姫鷹さくらへ避難誘導を命じ、寒椿狼星と寒月凍蝶も二人のもとへ向かう。",
    characters: ["花葉雛菊", "観鈴", "姫鷹さくら", "寒椿狼星", "寒月凍蝶"],
    keywords: ["華歳", "爆弾", "君命", "最終話", "避難誘導"],
    sourceUrl: "https://4seasons-anime.com/episode/",
  },
];
