export type CurrentProgram = {
  work:string;
  category:"ドラマ"|"バラエティ";
  episode:string;
  title:string;
  airtime:string;
  summary:string;
  people:string[];
  keywords:string[];
  sourceUrls:string[];
};

export const currentPrograms:CurrentProgram[] = [
  {work:"ぽかぽか",category:"バラエティ",episode:"8月20日放送",title:"夏特別企画 でんじろう生放送ドキドキ実験SP",airtime:"8月20日 11:47",summary:"音の不思議、ビーチボールの浮遊、アルミ箔を使った科学マジックなどを生放送で紹介し、風船爆弾を使った古今東西企画にも挑む。",people:["岩井勇気","澤部佑","神田愛花","島崎和歌子","佐々木大光","原田葵","米村でんじろう","ギャル曽根"],keywords:["夏特別企画","生放送","音の実験","ビーチボールの浮遊","アルミ箔の科学マジック","風船爆弾"],sourceUrls:["https://bangumi.org/tv_events/seasons?season_id=770855","https://www.fujitv.co.jp/pokapoka/"]},
  {work:"風、薫る",category:"ドラマ",episode:"第94回",title:"第19週 黎明の翼",airtime:"8月6日 7:45",summary:"りん、直美、黒川らの思いが村人に通じる一方、アサの容体は改善せず、厳しい状況が続く。",people:["りん","直美","黒川","アサ"],keywords:["黎明の翼","村人","容体"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260806&ggm_group_id=42"]},
  {work:"大空港〜GATE24〜",category:"ドラマ",episode:"第3話",title:"確認中",airtime:"8月6日 21:00",summary:"密輸された動物が逃げて審査ブースが封鎖される中、子どもを連れた女性が移動を拒む。万智たちは特別措置で、その場での審査に臨む。",people:["万智"],keywords:["密輸動物","審査ブース封鎖","子ども連れ","特別措置"],sourceUrls:["https://www.tv-asahi.co.jp/daikuukou/","https://post.tv-asahi.co.jp/post-812366/"]},
  {work:"ラストノート",category:"ドラマ",episode:"第5話",title:"確認中",airtime:"8月6日 22:00",summary:"葵は澄晴といる時だけ再び花の香りを感じる。十年以上前から香りが分からなくなった事情を明かすと、澄晴は協力を申し出る。",people:["葵","澄晴"],keywords:["花の香り","嗅覚","十年以上前","協力"],sourceUrls:["https://www.fujitv.co.jp/lastnote/story/"]},
  {work:"親愛なる夫へ",category:"ドラマ",episode:"第6話",title:"夫の罪、それぞれの秘密",airtime:"8月6日 23:59",summary:"田端とキャンプ中の優一は、妻は殺されたと告げられた直後、強い眠気で意識を失う。麻衣子は戻らない優一を捜し始める。",people:["優一","田端","麻衣子"],keywords:["キャンプ","妻は殺された","眠気","意識喪失","夫の罪"],sourceUrls:["https://www.ytv.co.jp/dear-husband/"]},
  {work:"突破ファイル",category:"バラエティ",episode:"8月6日放送",title:"スグやる課＆税関",airtime:"8月6日 19:00",summary:"スグやる課がシカの問題に挑み、税関ではDJにまつわる密輸の手口を追う。",people:["高橋文哉"],keywords:["スグやる課","シカ","税関","DJ","密輸"],sourceUrls:["https://www.ntv.co.jp/toppa/"]},
  {work:"ぐるぐるナインティナイン",category:"バラエティ",episode:"8月6日放送",title:"夏のコスプレフェス",airtime:"8月6日 19:54",summary:"夏のコスプレ企画を放送。詳細な企画構成は公式番組ページで確認中。",people:["ナインティナイン","高橋文哉"],keywords:["夏","コスプレフェス","確認中"],sourceUrls:["https://www.ntv.co.jp/gurunai/"]},
  {work:"ゴールデンタッグ",category:"バラエティ",episode:"8月6日放送",title:"異色コンビの二人旅",airtime:"8月6日 20:54",summary:"ダイアン津田と森七菜、M!LK曽野とさかなクン、永尾柚乃と熊元プロレスなど、異色の組み合わせが企画に挑む。",people:["津田篤宏","森七菜","曽野舜太","さかなクン","永尾柚乃","熊元プロレス"],keywords:["二人旅","異色コンビ","ガチャピン"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260806&ggm_group_id=42"]},
  {work:"相葉ヒロミのお困りですカー？",category:"バラエティ",episode:"2時間SP",title:"以前助けた人を再訪",airtime:"8月6日 19:00",summary:"相葉雅紀とヒロミが、以前手伝った人々のもとを再訪し、再び掃除などの困りごとを手伝う。",people:["相葉雅紀","ヒロミ"],keywords:["再訪","掃除","困りごと","2時間SP"],sourceUrls:["https://www.tv-asahi.co.jp/okomaridesucar/"]},
  {work:"この歌詞が刺さった！グッとフレーズ",category:"バラエティ",episode:"3時間SP",title:"夏に心アツくする名歌詞TOP30",airtime:"8月6日 19:00",summary:"夏に聴きたい、心を熱くする歌詞をランキング形式で紹介する。",people:["加藤浩次","大泉洋"],keywords:["夏","名歌詞","TOP30","ランキング"],sourceUrls:["https://www.tbs.co.jp/goodphrases/"]},
  {work:"櫻井・有吉THE夜会",category:"バラエティ",episode:"8月6日放送",title:"スターの私生活のぞき見SP",airtime:"8月6日 22:00",summary:"寺田心のボディーメイク、RIKACOと荒川の住まい、浅田舞とAYAの企画を取り上げる。",people:["櫻井翔","有吉弘行","寺田心","RIKACO","荒川","浅田舞","AYA"],keywords:["ボディーメイク","豪邸","私生活"],sourceUrls:["https://www.tbs.co.jp/tv/20260806_B71B.html"]},
  {work:"アメトーーク！",category:"バラエティ",episode:"8月6日放送",title:"懐かし回＆傑作回",airtime:"8月6日 23:45",summary:"配信中の過去回から懐かしい企画や傑作回を振り返る。紹介回の全内訳は確認中。",people:[],keywords:["懐かし回","傑作回","過去回","確認中"],sourceUrls:["https://www.tv-asahi.co.jp/ametalk/"]},
  {work:"風、薫る",category:"ドラマ",episode:"第109回",title:"第22週 明るい未来",airtime:"8月27日 7:45",summary:"小川の帰りを待つ直美は、美津やりんの力を借りながら育児に励む。",people:["直美","小川","美津","りん","上坂樹里","甲斐翔真","水野美紀","見上愛"],keywords:["明るい未来","小川の帰り","育児"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.nhk.jp/p/asa-kaze/ts/JPV1KGVQXX/"]},
  {work:"突破ファイル",category:"バラエティ",episode:"8月27日放送",title:"猛暑のトラブル大解決2時間SP",airtime:"8月27日 19:00",summary:"突破不動産が怪音やカラスの問題に挑み、突破国税局はホテルの脱税疑惑を追う。田中教授のフシギ事件簿も放送する。",people:["内村光良","サンドウィッチマン","男性ブランコ","星野真里","松尾諭","レインボー"],keywords:["突破不動産","カラス","怪音","突破国税局","ホテル脱税","田中教授"],sourceUrls:["https://bangumi.org/tv_events/AmAAQQIaEAM?overwrite_area=23","https://www.ntv.co.jp/toppa/"]},
  {work:"見取り図の間取り図ミステリー！",category:"バラエティ",episode:"8月27日放送",title:"大家族＆激安移住スペシャル",airtime:"8月27日 22:00",summary:"子ども7人の大家族が暮らす独自の間取りと、人口増加率が高い北海道の地域にある激安物件の秘密を取り上げる。",people:["見取り図"],keywords:["大家族","独自の間取り","北海道","激安物件","移住"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.ytv.co.jp/madorizu/"]},
  {work:"親愛なる夫へ",category:"ドラマ",episode:"最終回",title:"確認中",airtime:"8月27日 23:59",summary:"夫が隠し続けてきた秘密と妻の嘘、妻を殺した犯人をめぐる全ての真実が明らかになり、別れの時が迫る。",people:["優一","麻衣子"],keywords:["最終回","全ての真実","妻の死","夫の秘密","妻の嘘","犯人"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.ytv.co.jp/dear-husband/"]},
  {work:"相葉ヒロミのお困りですカー？",category:"バラエティ",episode:"2時間SP（8月27日）",title:"三崎のマグロを守れ！冷凍庫の大掃除",airtime:"8月27日 19:00",summary:"相葉雅紀とヒロミが、マイナス60度の冷凍庫を大掃除し、巨大な氷の除去に挑む。",people:["相葉雅紀","ヒロミ"],keywords:["三崎","マグロ","マイナス60度","冷凍庫","大掃除","モンスター氷"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.tv-asahi.co.jp/okomaridesucar/"]},
  {work:"大空港〜GATE24〜",category:"ドラマ",episode:"第6話",title:"確認中",airtime:"8月27日 21:00",summary:"違法カジノ摘発後に胴元側の女性が逃亡し、違法薬物の持ち込み情報も入る。妻の骨壺を抱えて帰国した高瀬を審査する万智は、荷物に小さな違和感を見つける。",people:["森万智","高瀬佑磨","深澤","紬","趣里","清水伸","柳葉敏郎","泉有乃"],keywords:["違法カジノ","違法薬物","妻の骨壺","荷物の違和感","娘の見送り"],sourceUrls:["https://bangumi.org/tv_events/AmAAQoGxAAM?overwrite_area=23","https://www.tv-asahi.co.jp/daikuukou/"]},
  {work:"アメトーーク！",category:"バラエティ",episode:"8月27日放送",title:"東京吉本芸人の実情〜我々は30年、間違い続けたのか〜",airtime:"8月27日 23:15",summary:"大阪吉本と比べてまとまらなかった東京吉本の30年を、屋敷裕政のプレゼンと芸人たちの証言で振り返り、新たなリーダーを考える。",people:["蛍原徹","ニューヨーク","吉村崇","長田庄平","野田クリスタル","向井慧","山添寛","ジャンボたかお","千鳥"],keywords:["東京吉本","大阪吉本","30年","負の歴史","新リーダー"],sourceUrls:["https://bangumi.org/tv_events/AmAAQoGxMAM?overwrite_area=23","https://www.tv-asahi.co.jp/ametalk/"]},
  {work:"プレバト！！",category:"バラエティ",episode:"2時間SP（8月27日）",title:"ガラスアート・色鉛筆・ラブレター俳句",airtime:"8月27日 19:00",summary:"ガラスアートと色鉛筆の査定に加え、「好きな人」を題材にしたラブレター俳句へ出演者が挑戦する。",people:["浜田雅功","辻元舞","くっきー！","梅沢富美男"],keywords:["ガラスアート","色鉛筆","ラブレター俳句","好きな人"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.mbs.jp/p-battle/"]},
  {work:"櫻井・有吉THE夜会",category:"バラエティ",episode:"8月27日放送",title:"冷食を愛する人たちの夜会",airtime:"8月27日 22:00",summary:"冷凍食品の愛好家が選ぶベストバイと、手軽に作れる冷凍食品のアレンジ料理を紹介する。",people:["櫻井翔","有吉弘行"],keywords:["冷凍食品","ベストバイ","冷食アレンジ飯"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.tbs.co.jp/the-yakai/"]},
  {work:"カンブリア宮殿",category:"バラエティ",episode:"8月27日放送",title:"ヒットメーカーの創作術 脚本家・三谷幸喜",airtime:"8月27日 23:06",summary:"脚本家・三谷幸喜の発想法と、仕事に応用できる創作術を取り上げる。",people:["三谷幸喜","村上龍","小池栄子"],keywords:["ヒットメーカー","脚本家","創作術","発想法","仕事術"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.tv-tokyo.co.jp/cambria/"]},
  {work:"ナゾトレMAXXX",category:"バラエティ",episode:"8月27日放送",title:"新学期直前！文房具SP",airtime:"8月27日 21:00",summary:"文具女子博に出展したメーカー社員へ調査し、使って感動した他社の文房具トップ10やヒット商品の秘密を紹介する。",people:[],keywords:["文房具","文具女子博","メーカー社員","トップ10","マッキー"],sourceUrls:["https://bangumi.org/epg/td?broad_cast_date=20260827&ggm_group_id=42","https://www.fujitv.co.jp/nazotore/"]},
  {work:"ラストノート",category:"ドラマ",episode:"第8話",title:"現実が恋を阻む…あなたを諦めたくない…",airtime:"8月27日 22:00",summary:"想いを確かめ合った葵と澄晴。莉奈は葵へ澄晴を返すよう迫り、澄晴は絵画教室でアシスタントの仕事を提案される。葵は元夫に20歳差の恋を打ち明ける。",people:["一瀬葵","樋口澄晴","木嶋莉奈","二宮慶太郎","奥田創","内田有紀","寺西拓人","桜井日奈子"],keywords:["20歳差","莉奈の抗議","絵画教室","アシスタント","元夫への告白"],sourceUrls:["https://bangumi.org/tv_events/AmAAQg870AM?overwrite_area=23","https://www.fujitv.co.jp/lastnote/story/"]},
];
